### ISSUE TITLE
Spanish voice pleaseeee

### ISSUE THREAD

**Issue by Blizzeffect** [instafluff/HighlightOfMyChat#12]
Can you please add Sara (spanish) voice to the parameters? My chat speaks spanish and the LOVE they extension even without this<3

**Comment by Vuurvos1** [comment]
The current API we are using for the text to speech doesn't have a Sara voice. It does include a few other Spanish voices though:

- Enrique, male, Spanish European
- Conchita, female, Spanish European
- Lucia, female, Spanish European
- Mia, female, Spanish Mexican
- Miguel, male, Spanish American
- Penélope, male, Spanish American

If you want to learn some more about the voices you can read the 256-page documentation [here ](https://docs.aws.amazon.com/polly/latest/dg/polly-dg.pdf) but on pages 18-20 should be all the information you need.

**Comment by Blizzeffect** [comment]
> The current API we are using for the text to speech doesn't have a Sara voice. It does include a few other Spanish voices though:
> 
> * Enrique, male, Spanish European
> * Conchita, female, Spanish European
> * Lucia, female, Spanish European
> * Mia, female, Spanish Mexican
> * Miguel, male, Spanish American
> * Penélope, male, Spanish American
> 
> If you want to learn some more about the voices you can read the 256-page documentation [here ](https://docs.aws.amazon.com/polly/latest/dg/polly-dg.pdf) but on pages 18-20 should be all the information you need.

Thanks a LOT, you made my day <3
