### ISSUE TITLE
Change voice for different language

### ISSUE THREAD

**Issue by vitt0** [instafluff/HighlightOfMyChat#2]
Hi there,

I'll like to know it's possible to configure the voice to be in another language that english? 
I'll like to use a portuguese for example. 

Greetings.

Edit: I saw that you guys are using StreamElements API for the TTS, so I tried to set the voice as "Vitoria" (one of the voices for Portuguese, also Ricardo for male) in the link:

"https://www.instafluff.tv/HighlightOfMyChat?channel=xxxxxx&tts=true&voice=Vitoria"

And it worked 👍

**Comment by instafluff** [comment]
Great!! I'm glad it worked for you!
