### ISSUE TITLE
Cannot seem to get the program working

### ISSUE THREAD

**Issue by malconer** [instafluff/HighlightOfMyChat#7]
Hi there,

I am very green when it comes to coding so I do not really understand what I am doing. I followed the steps as described, but for some reason I do not have any sound output. Any help would be really appreciated. Otherwise really great work, I have seen it work for other streamers. Keep doing what You are doing.

Greetings

**Comment by Vuurvos1** [comment]
Can you give some more information on your setup? For example, which browser are you using and which URL?

**Comment by malconer** [comment]
I am using Microsoft Edge, since the new version is a ton better and uses less ram than Chrome.
I was messing around with this URL: 

https://www.instafluff.tv/HighlightOfMyChat?channel=malconers&tts=true&voice=Brian&bottom=true&texttimer=10000

I tried Amy as voice as well.

**Comment by jonathan-bryant** [comment]
I'm getting this error if that helps. Messages appear but TTS isn't working
![image](https://user-images.githubusercontent.com/16954813/87855093-6317d500-c959-11ea-8899-71824ef0223d.png)

**Comment by malconer** [comment]
Ah yes, I do have the same issue. A message appears if I make the window visible. TTS is not working.

**Comment by Vuurvos1** [comment]
So I did some investigating and the problem is with the Streamelements TTS API specifically, once a request is made to this API it gets blocked by the CORS policy. There might be workarounds for this problem by routing the request through a server instead of the browser. I put a bit of time into trying to fix the issue but no success yet.
Some more info on this: [CORS ](https://developer.mozilla.org/nl/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default), [Possible solutions](https://medium.com/@dtkatz/3-ways-to-fix-the-cors-error-and-how-access-control-allow-origin-works-d97d55946d9)

I did use your link in the [Brave](https://brave.com/) browser and there it seemed to work fine, 
Some other interesting things to note is that you have to have interacted with the page before it can play audio

**Comment by malconer** [comment]
Okay, thanks a lot for the help. How exactly do I have to interact with the page? When I open the link in the browser it remains white.

**Comment by malconer** [comment]
I will use the Brave browser for this. Thanks again very much.

Take care and keep doing what You are doing!

**Comment by Vuurvos1** [comment]
Just clicking the page once should do the job, also the Brave browser might work for me but isn't a 100% guaranty that it will work for everyone. Could you send a response if that works for you?

**Comment by malconer** [comment]
Yes the Brave browser does work for me.

**Comment by DennisTerrell** [comment]
Also affected by this `CORS` issue.

![Annotation 2020-07-19 124047](https://user-images.githubusercontent.com/3598633/87883638-a146e000-c9bd-11ea-9b58-19b88d20d7e6.jpg)

Been using this in SLOBS as a browser source in a couple scenes. Now it seems the request is blocked.

After putting the request url in Chromium you have to do the StreamElements captcha and then the request is honored and the text is played. 

Please advise.

**Comment by Vuurvos1** [comment]
For now, using [Brave](https://brave.com/) seems to work but that is only a temporary fix. I am looking into a more permanent fix for the issue but that might take a while.

**Comment by DennisTerrell** [comment]
Hrm, not sure how you would make the request from Brave via SLOBS.

Thanks for attempting to work up a solution @Vuurvos1. I'm guessing some sort of proxy would need to be added in order to wrap the request with the appropriate header.

**Comment by instafluff** [comment]
Thanks for finding a workaround. We might be able to piggy-back from a browser TTS but the voices would be different and won't sound good. If anyone has a better solution, please feel free to suggest!

**Comment by Vuurvos1** [comment]
I was also thinking about using browser TTS but on Windows, you would only have 2 voices unless you are using Google Chrome where you have access to the same voices as you would in Google Translate.

**Comment by Vuurvos1** [comment]
I think I fixed the issue and the code can be downloaded [here](https://github.com/Vuurvos1/HighlightOfMyChat/tree/hotfix/corsError). If you download the code and open the `index.html` and then change the properties in the URL to fit your needs you can test it, for example: `index.html?channel=username&tts=true`. Please let me know if you find any more issues.

**Comment by malconer** [comment]
Sorrt for I am being a little dumb at this. I am a little bit confused, since it still only works with the browser opened (or it should work like that). I tried a couple of different URLs. 
https://www.instafluff.tv/HighlightOfMyChat/index.html?bottom=true&channel=malconers&texttimer=10000&tts=true&voice=Brian
Is this the URL I was supposed to use?

file:///C:/Users/Kasutaja/Desktop/HighlightOfMyChat-hotfix-corsError/index.html?bottom=true&channel=malconers&texttimer=10000&tts=true&voice=Brian

https://www.instafluff.tv/HighlightOfMyChat-hotfix-corsError/index.html?bottom=true&channel=malconers&texttimer=10000&tts=true&voice=Brian
also tried these. Thank you a lot for your patience.

**Comment by Vuurvos1** [comment]
The code with my fix isn't live yet, so using the `https://www.instafluff.tv` URL won't have my changes. If you use the link with `file:///C:.....` it should work.

**Comment by instafluff** [comment]
It should be working now! Thank you again @Vuurvos1 for 9eea3c7e26858e84bd0e2558d8a17d310ba94de9

**Comment by malconer** [comment]
Thank You guys a lot for the help!
